# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      publish:
        description: 'publish or not'
        default: false
        type: boolean
        required: true
      version:
        description: 'npm packages version'
        default: ''
        required: false
      tag:
        description: 'npm packages tag (next or latest)'
        default: 'next'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - uses: nrwl/nx-set-shas@v3
      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"
      - run: npm ci
      - run: npx nx workspace-lint
      - run: npx nx format:check
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
      - name: 'publish to npm'
        if: ${{github.event.inputs.publish}}
        run: npx nx run-many --target=publish --ver ${{github.event.inputs.version}} --tag  ${{github.event.inputs.tag}} --parallel=3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
